apiVersion: v1
kind: Service
metadata:
  name: logger-service
  namespace: logger
spec:
  selector:
    app: logger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
